config/routes.rb
Rails.application.routes.draw do
  resources :pictures do
    collection do
      post :confirm
    end
  end
  resources :users
  resources :sessions, only:[:new, :create, :destroy]
  resources :favorites, only: [:index, :create, :destroy]
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :picture
end

app/models/picture.rb
class Picture < ApplicationRecord
  mount_uploader :image, ImageUploader

  validates :title, :content, length: { in: 1..140 }
  validates :image, presence: true
  has_many :favorites, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, length: {maximum: 30}
  validates :email, presence: true, length: {maximum: 255}, format: {with:/\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i}
  before_validation { email.downcase! }
  has_secure_password
  validates :password, presence: true, length: { minimum:6 }

  has_many :favorites, dependent: :destroy
  has_many :pictures
  mount_uploader :icon, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def index
    @user = current_user
    @favorite = @user.favorites
  end
  def create
    favorite = current_user.favorites.create(picture_id: params[:picture_id])
    redirect_to pictures_path, notice: "#{favorite.picture.user.name}さんの写真をお気に入り登録したよ！"
  end

  def destroy
    favorite = current_user.favorites.find_by(id: params[:id]).destroy
    redirect_to pictures_path, notice: "#{favorite.picture.user.name}さんの写真をお気に入り解除したよ！"
  end

end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :set_picture, only:[:show, :update, :destroy]
  before_action :user_check, only:[:edit]
  def index
    @pictures = Picture.all
  end

  def new
    if params[:back]
      @picture = Picture.new(picture_params)
    else
      @picture = Picture.new
    end
  end

  def create
    @picture = Picture.new(picture_params)
    @picture.user_id = current_user.id
    if @picture.save
      redirect_to pictures_path, notice: "投稿したよ！"
    else
      render 'new'
    end
  end

  def show
    @favorite = current_user.favorites.find_by(picture_id: @picture.id)
  end

  def edit
  end

  def update
    if @picture.update(picture_params)
      redirect_to pictures_path, notice: "写真を編集したよ！"
    else
      render 'edit'
    end
  end

  def destroy
    @picture.destroy
    redirect_to pictures_path, notice:"投稿を削除しました！"
  end

  def confirm
    @picture = Picture.new(picture_params)
    @picture.user_id = current_user.id
    render :new if @picture.invalid?
  end

  private

  def picture_params
    params.require(:picture).permit(:title, :content, :image, :image_cache)
  end

  def set_picture
    @picture = Picture.find(params[:id])
  end

  def user_check
    @picture_id = Picture.find(params[:id]).user_id
    if @picture_id == current_user.id
      @picture = Picture.find(params[:id])
    else
      redirect_to pictures_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
  def choose_new_or_edit
    if action_name == 'new'||action_name == 'confirm'
      confirm_pictures_path
    elsif action_name == 'edit'
      picture_path
    end
  end
end

app/views/favorites/index.html.erb
  <h3>お気に入り一覧</h3>
<% @favorite.each do |favorite| %>
<div class="box">
  <ul class="list">
      <li class="user"><div id="user_img"><%= image_tag(favorite.picture.user.icon.url) %></div><%= favorite.picture.user.name %></li>
      <li><%= favorite.picture.title %></li>
      <li><%= image_tag(favorite.picture.image.url) %></li>
      <li><%= favorite.picture.content %></li>
  </ul>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rubistagram</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <ul>
      <% if logged_in? %>
        <li><%= link_to "Top", pictures_path %></li>
        <li><%= link_to "New", new_picture_path %></li>
        <li><%= link_to "Profile", user_path(current_user.id) %></li>
        <li><%= link_to "Favorites", favorites_path  %>
        <li><%= link_to "Logout", session_path(current_user.id), method: :delete %></li>
      <% else %>
        <li><%= link_to "Sign up", new_user_path %></li>
        <li><%= link_to "Login", new_session_path %></li>
      <% end %>
    </header>
    <section class="main-header">
      <%= yield %>
    </section>
    <footer>
      <p>pompompurin</p>
    </footer>
  </body>
</html>

app/views/pictures/_form.html.erb
<%= form_with(model: @picture, local: true, url: choose_new_or_edit) do |form| %>
  <% if @picture.errors.any? %>
    <div id="error_explenation">
      <h2><%= @picture.errors.count %>件のエラーがあるよ(T T)</h2>
      <ul>
        <% @picture.errors.full_messages.each do |msg| %>
        <li class="error_li"><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="picture_title">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="pictire_content">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>

  <div class="new-image">
    <%= form.label :image %>
    <%= image_tag(@picture.image.url) if @picture.image.url %>
    <%= form.file_field :image %>
  </div>

  <%= form.submit %>
<% end %>

<%= form_with(model: @picture, url: new_picture_path, local: true, method: 'get') do |form| %>
  <%= form.hidden_field :title %>
  <%= form.hidden_field :image %>
  <%= form.hidden_field :content %>
  <%= form.submit "BACK", name: 'back' %>
<% end %>

app/views/pictures/confirm.html.erb
<%= form_with(model: @picture, url:pictures_path, local: true) do |form| %>
  <%= form.hidden_field :title %>
  <%= form.hidden_field :image_cache %>
  <%= form.hidden_field :content %>

  <p><%= @picture.title %></p>
  <p><%= @picture.content %></p>
  <p><%= image_tag(@picture.image.url) %></p><br>
  <%= form.submit "登録" %>
<% end %>

app/views/pictures/edit.html.erb
<h1>投稿の編集</h1>

<%= render 'form' %>

app/views/pictures/index.html.erb
<h1>Time Line</h1>

<p>
<% flash.each do |key, value| %>
   <%= content_tag(:div, value, class: "#{key}") %>
<% end %>
</p>
<% @pictures.each do |picture| %>
<div class="box">
  <ul class="list">
    <li class="user"><div id="user_img"><%= image_tag(picture.user.icon.url) %></div><%= picture.user.name %></li>
    <li><h3><%= picture.title %></h3></li>
    <li class="image"><%= image_tag(picture.image.url) %></li>
    <li><%= picture.content %></li>
  </ul>
  <button type="button" class="btn btn-outline-info"><%= link_to 'Detail', picture_path(picture.id) %></button>
  <% if picture.user_id == current_user.id %>
    <button type="button" class="btn btn-outline-warning"><%= link_to 'Edit', edit_picture_path(picture.id), data: {confirm: 'Are you sure？'} %></button>
    <button type="button" class="btn btn-outline-warning"><%= link_to 'Dlete', picture_path(picture.id), method: :delete %></button>
  <% end %>
  <br>
</div>
<% end %>

app/views/pictures/new.html.erb
<h1>写真を投稿する</h1>

<%= render 'form' %>

app/views/pictures/show.html.erb
<h3><%= @picture.title %></h3>
<p><%= image_tag @picture.image.url if @picture.image.present? %></p>
<p><%= @picture.content %></p>


<% unless @picture.user_id == current_user.id %>
  <% if @favorite.present? %>
    <%= link_to '❤️', favorite_path(id: @favorite.id), method: :delete %>
  <% else %>
    <%= link_to '💛', favorites_path(picture_id: @picture.id), method: :post %>
  <% end %>
<% end %>
<%= link_to 'Back', pictures_path %>